// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD11Jf2stoSVQ6YqGAe9v-VdYVO1l8Uobo',
    appId: '1:737617778809:web:e830adc0de0243d81edca8',
    messagingSenderId: '737617778809',
    projectId: 'ecommerce-d9e8c',
    authDomain: 'ecommerce-d9e8c.firebaseapp.com',
    storageBucket: 'ecommerce-d9e8c.appspot.com',
    measurementId: 'G-P2J2T580G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxdJ7atbLdzfSKZqXwlYvLH3XGevuyYc',
    appId: '1:737617778809:android:d7e2ea6fc0b5dad11edca8',
    messagingSenderId: '737617778809',
    projectId: 'ecommerce-d9e8c',
    storageBucket: 'ecommerce-d9e8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcfiqPaPLpSCgrmurhxevgzXCdzXovPU',
    appId: '1:737617778809:ios:ee1e33f163fa481b1edca8',
    messagingSenderId: '737617778809',
    projectId: 'ecommerce-d9e8c',
    storageBucket: 'ecommerce-d9e8c.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcfiqPaPLpSCgrmurhxevgzXCdzXovPU',
    appId: '1:737617778809:ios:4ba3593b7f373dfe1edca8',
    messagingSenderId: '737617778809',
    projectId: 'ecommerce-d9e8c',
    storageBucket: 'ecommerce-d9e8c.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
